name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET 7.0 SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x

    - name: Publish .NET Project
      run: dotnet publish src/Oligopoly.WebAssembly/Oligopoly.WebAssembly.csproj -c Release -o release --nologo

    - name: Change base-tag in index.html from / to oligopoly
      run: sed -i 's/<base href="\/" \/>/<base href="\/oligopoly\/" \/>/g' release/wwwroot/index.html

    - name: copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
